### ISSUE TITLE
Do not call telemetryClient.Flush(); from the sink

### ISSUE THREAD

**Issue by SergeyKanzhelev** [fidmor89/SLAB_AppInsights#4]
Do not call `telemetryClient.Flush();` from the [sink](https://github.com/fidmor89/SLAB_AppInsights/blob/master/SLAB_AI/SLAB_AI/Sinks/ApplicationInsightsSink.cs#L133)  Let channel manage buffering - it will do it more efficient if it will not need to initiate sending after every trace statement. If you need to call Flush - call it from the test application itself or implement destructor for the sink.

**Comment by fidmor89** [comment]
Ok, so I understand that the channel will manage the buffering by its own.  Then by simply removing `telemetryClient.Flush();` from the [code](https://github.com/fidmor89/SLAB_AppInsights/blob/master/SLAB_AI/SLAB_AI/Sinks/ApplicationInsightsSink.cs#L133) would allow the channel to make an auto flush? or should I implement it somewhere else?

**Comment by SergeyKanzhelev** [comment]
My guess you have Flush in a sink because otherwise console test application will be closed before events are sent. So I recommend to use Flush in test application itself

**Comment by fidmor89** [comment]
No, its in the sink because we thought that was the right way to push the event. I been reading some blogs and I found that the AI SDK should send data by it self at time intervals chosen to minimize impact on the user and that Flush should be used only when the SDK is used in an applications that shuts down.
So what I get is:
1. I should remove the Flush method from the sink
2. Let the user choose choose when the Flush is necessary.

I'm I right?

**Comment by SergeyKanzhelev** [comment]
Exactly! Thanks!

**Comment by fidmor89** [comment]
Thanks for the help it was solved with Commit a1fbb4f4
